import type { Offer } from './offer.model';

export const MOCK_OFFERS: Offer[] = [
  {
    id: 'offer-espresso-maker',
    title: 'Compact Espresso Maker',
    description: '15-bar pump espresso machine with steam wand. Perfect for small kitchens.',
    imageUrl: 'https://picsum.photos/seed/offer-espresso-maker/900/600',
    price: 129.99,
    rating: 4.2,
    votes: 12,
    purchaseUrl: 'https://example.com/products/espresso-maker',
  },
  {
    id: 'offer-noise-cancelling-headphones',
    title: 'Noise-Cancelling Headphones',
    description: 'Wireless over-ear headphones with active noise cancellation and 30h battery.',
    imageUrl: 'https://picsum.photos/seed/offer-noise-cancelling-headphones/900/600',
    price: 249.0,
    rating: 4.6,
    votes: 35,
    purchaseUrl: 'https://example.com/products/noise-cancelling-headphones',
  },
  {
    id: 'offer-smart-lamp',
    title: 'Smart LED Desk Lamp',
    description: 'Dimmable LED lamp with color temperature control and USB-C charging port.',
    imageUrl: 'https://picsum.photos/seed/offer-smart-lamp/900/600',
    price: 49.5,
    rating: 4.0,
    votes: 5,
    purchaseUrl: 'https://example.com/products/smart-lamp',
  },
  {
    id: 'offer-mechanical-keyboard',
    title: 'Mechanical Keyboard (Hot-Swappable)',
    description: '75% layout with RGB backlight, hot-swappable switches, and PBT keycaps.',
    imageUrl: 'https://picsum.photos/seed/offer-mechanical-keyboard/900/600',
    price: 99.0,
    rating: 4.4,
    votes: -2,
    purchaseUrl: 'https://example.com/products/mechanical-keyboard',
  },
  {
    id: 'offer-french-press',
    title: 'Borosilicate French Press',
    description: '1L heat-resistant glass, stainless-steel filter for rich, full-bodied coffee.',
    imageUrl: 'https://picsum.photos/seed/offer-french-press/900/600',
    price: 29.95,
    rating: 3.8,
    votes: 0,
    purchaseUrl: 'https://example.com/products/french-press',
  },
  {
    id: 'offer-smart-speaker',
    title: 'Smart Speaker Mini',
    description: 'Compact smart speaker with voice assistant and multi-room audio support.',
    imageUrl: 'https://picsum.photos/seed/offer-smart-speaker/900/600',
    price: 59.99,
    rating: 4.1,
    votes: 8,
    purchaseUrl: 'https://example.com/products/smart-speaker',
  },
  {
    id: 'offer-robot-vacuum',
    title: 'Robot Vacuum Cleaner',
    description: 'Self-charging robot vacuum with mapping and 120-minute runtime.',
    imageUrl: 'https://picsum.photos/seed/offer-robot-vacuum/900/600',
    price: 279.99,
    rating: 4.5,
    votes: 21,
    purchaseUrl: 'https://example.com/products/robot-vacuum',
  },
];
